### Pandas-DataFrame And Series

#### Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogenous tabular data structure with labeled axes(rows and cloumns).

In [2]:
import pandas as pd

In [4]:
### Series
### Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
### Create a series from a dictionary
data = {
    'a':1,
    'b':2,
    'c':3
}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data=[10,20,40]
idx=['a','b','c']
pd.Series(data,index=idx)

a    10
b    20
c    40
dtype: int64

In [19]:
### DataFrame
### create a DataFrame from a dictionary of list

data1={
    'Name':['Rahul','John','Jack'],
    'Age':[25,30,45],
    'City':['Kochi','Bangalore','Kolkata']
}
df1 = pd.DataFrame(data)
print(df1)
print(type(df1))

    Name  Age       City
0  Rahul   25      Kochi
1   John   30  Bangalore
2   Jack   45    Kolkata
<class 'pandas.DataFrame'>

In [20]:
### Create a dataframe from a list of dictionaries

data = [
    {'Name':'John', 'Age':23, 'City':'Texas'},
    {'Name':'Jack', 'Age':25, 'City':'Florida'},
    {'Name':'Jones', 'Age':27, 'City':'Kolkata'},
    {'Name':'Smith', 'Age':26, 'City':'Georgia'}
]
df2 = pd.DataFrame(data)
print(df2)

    Name  Age     City
0   John   23    Texas
1   Jack   25  Florida
2  Jones   27  Kolkata
3  Smith   26  Georgia

In [22]:
df3=pd.read_csv("sample_data.csv")
df3.head(5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [23]:
df3.tail(5)

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [14]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [24]:
### Accessing data from DataFrame
df1

    Name  Age       City
0  Rahul   25      Kochi
1   John   30  Bangalore
2   Jack   45    Kolkata

In [26]:
df1['Name']

0    Rahul
1     John
2     Jack
Name: Name, dtype: str

In [ ]:
df1.loc[0]  ### Returns the row at index 0

Name    Rahul
Age        25
City    Kochi
Name: 0, dtype: object

In [ ]:
df1.iloc[0]  ### returns the row at position 0

Name    Rahul
Age        25
City    Kochi
Name: 0, dtype: object

In [29]:
df1

    Name  Age       City
0  Rahul   25      Kochi
1   John   30  Bangalore
2   Jack   45    Kolkata

In [32]:
### Accessing a specified element
print(df1.at[2,'Age'])

45

In [34]:
print(df1.iat[2,2])

Kolkata

In [35]:
### Data Manipulation with DataFrame
df1

    Name  Age       City
0  Rahul   25      Kochi
1   John   30  Bangalore
2   Jack   45    Kolkata

In [36]:
### Adding a column
df1['Salary'] = [50000,60000,70000]
df1

    Name  Age       City  Salary
0  Rahul   25      Kochi   50000
1   John   30  Bangalore   60000
2   Jack   45    Kolkata   70000

In [40]:
### Remove a column temporarily

df1.drop('Salary',axis=1)

    Name  Age       City
0  Rahul   25      Kochi
1   John   30  Bangalore
2   Jack   45    Kolkata

In [41]:
df1

    Name  Age       City  Salary
0  Rahul   25      Kochi   50000
1   John   30  Bangalore   60000
2   Jack   45    Kolkata   70000

In [43]:
### removing a column permanently

df1.drop('Salary', axis=1, inplace=True)

In [44]:
df1

    Name  Age       City
0  Rahul   25      Kochi
1   John   30  Bangalore
2   Jack   45    Kolkata

In [45]:
### Increment the Age column
df1['Age']=df1['Age']+1
df1

    Name  Age       City
0  Rahul   26      Kochi
1   John   31  Bangalore
2   Jack   46    Kolkata

In [46]:
### Deleting first row
df1.drop(0, inplace=True)

In [47]:
df1

   Name  Age       City
1  John   31  Bangalore
2  Jack   46    Kolkata

In [49]:
df4=pd.read_csv('sample_data.csv')
df4.head(5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [51]:
### Display the types of each column
print("Data types:\n", df4.dtypes)

### Describe the DataFrame
print("Statistical Summary:\n", df4.describe())

Data types:
 Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object
Statistical Summary:
          Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [52]:
df4.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000